### ISSUE TITLE
关于运行速度

### ISSUE THREAD

**Issue by jettywang1020** [Freemanzxp/GBDT_Simple_Tutorial#3]
首先非常感谢这个详细教程，但是有个问题，为什么我在跑这个tutorial代码的时候这么慢呢？在数据量这么少并且只迭代5次的情况下。

real	3m27.845s
user	3m27.134s
sys	0m2.053s

**Comment by foreverfc1994** [comment]
导致这个问题的主要原因可能是在树的展示上。单纯运行代码而不展示树是很快的，同时图片的存储也花费了一定的时间。

**Comment by jettywang1020** [comment]
@foreverfc1994 了解了，再次感谢！

**Comment by Peishiyu** [comment]
只需要把参数arg.plot=False，就很快，没有图片，只有log
